# Basic Site Settings
locale                   : "en-US"
title                    : "Ritika Verma"
title_separator          : "-"
name                     : "Ritika Verma"
description              : "PhD Student in Economics | NYU"
url                      : https://ritikaverma2179.github.io
baseurl                  : ""
repository               : "ritikaverma2179/ritikaverma2179.github.io"

# Site Author - The following control what appear as part of the author content on the side bar
author:
  avatar           : "images/my_photo.png"  # Ensure the photo is in the correct location
  name             : "Ritika Verma"
  bio              : "I am a PhD student in Economics at NYU. My research interests include Microeconomic Theory, Corporate Finance, and Innovation Markets."
  location         : "New York, NY, USA"
  employer         : "New York University"
  email            : "rv2179@nyu.edu"
  cv               : "/files/CV_RitikaVerma.pdf"  # Link to your CV

# Academic Websites (Optional for future)
arxiv            : ""  # URL - update once you have a profile
googlescholar    : ""
researchgate     : ""

# Publications Section
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Manuscripts'
  conferences:
    title: 'Conference Papers'

# Site Settings
teaser                   : "500x300.png"  # Optional image for teaser, placed in /images/
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
comments:
  provider               : "disqus"  # Enable for comments on posts if desired

# Social Media Links
linkedin         : "https://www.linkedin.com/in/ritika-verma-49bb5614a"
twitter          : "https://x.com/ritikav06234649?lang=cs"

# CV Section - Ensure this file exists at /files/CV_RitikaVerma.pdf
files:
  - CV_RitikaVerma.pdf

# Section for CV, Papers, and Research
collections:
  cv:
    output: true
    permalink: /cv/
  research:
    output: true
    permalink: /research/

# Plugins for enhanced functionality
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archive settings
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
